### ISSUE TITLE
thread terminated 

### ISSUE THREAD

**Issue by joey5403** [mierak/rmpc#161]
### Description

thread terminated when i wanna change to the Artists List.

### Steps to reproduce

open rmpc
press 3

### What terminal emulator are you running rmpc in?

wezterm 20240203-110809-5046fc22

### rmpc debuginfo

thread 'main task' has overflowed its stack
fatal runtime error: stack overflow
fish: Job 1, 'rmpc' terminated by signal SIGABRT (Abort)

### Relevant log output

[rmpc.log](https://github.com/user-attachments/files/17870197/rmpc.log)

**Comment by mierak** [comment]
I am unable to reproduce this issue. It seems that MPD is closing the connection to rmpc to which rmpc reacts with an attempt to reconnect and this cycle repeats endlessly.

Is rmpc the only client which exhibits this behaviour? What is your MPD config? Do you have `max_connections` or `connection_timeout `?

**Comment by joey5403** [comment]
1. there is no error when i use ncmpcpp. 
2. the "Queue" and "Directories" are normal, without restart mpd.
3. my Artists list is very long maybe 1000 item in it.

**Comment by mierak** [comment]
I tried rmpc with 10 000 artists over network on my old rpi3 and it seems to handle it just fine

<details>
<summary>10 000 artists in rmpc</summary>

![image](https://github.com/user-attachments/assets/a5457326-e3f1-40cf-a658-f50fdd2e797e)

</details>

You mention MPD restart, does it crash? Is there anything relevant in MPD's logs?

**Comment by joey5403** [comment]
![image](https://github.com/user-attachments/assets/1d8a75ca-a0ed-4d39-90d5-ab981e8ceccc)

i can debug and reproduce it. 

but i'm not a rust coder,

maybe you can tell me how to get more info of it.

**Comment by mierak** [comment]
Sorry for taking so long to respond, I have merged big changes to how rmpc connects to MPD, can you please try to build from master if anything changed for better or worse on your end?

**Comment by joey5403** [comment]
still the same error.

![image](https://github.com/user-attachments/assets/838123c0-8412-4874-a6ec-9bb20aebe922)
[rmpc.log](https://github.com/user-attachments/files/18032147/rmpc.log)

**Comment by mierak** [comment]
Thanks, can you try again from master with https://github.com/mierak/rmpc/pull/170 merged? Should either fix it or give us a better idea. Either way it should stop the endless reconnect loop.

**Comment by joey5403** [comment]
thanks a lot for fix it.
when i use the latest master and open the Artists List. 
didn't crash and get this error.
![image](https://github.com/user-attachments/assets/163646ca-410c-4126-be40-301e626cebeb)

log in /tmp/rmpc.log
``` 
2024-12-06T12:54:51.118092660Z ERROR thread=main src/main.rs:572 message="GenericError: 'stream did not contain valid UTF-8'"
```

**Comment by joey5403** [comment]
fixed
