### ISSUE TITLE
tmux weird behaviour when alt-[ is a binding

### ISSUE THREAD

**Issue by aris-mav** [mierak/rmpc#744]
### Description

In my tmux config, I have `bind-key -n M-[ copy-mode`, to enter copy mode with alt-[.

When I run `rmpc` tmux enters copy mode and `(search-up)`, followed by `(repeat)`, as if I pressed `alt-[-?` plus something else I can't figure out. After clicking enter a few times I finally exit the tmux copy mode and enter the rmpc TUI.

I tested a similar setup on wezterm, where I got the same alt-[ keybinding for its native copy mode, and the issue does not exist, things just work.

### Steps to reproduce

Install tmux and rmpc from pacman on Arch, add `bind-key -n M-[ copy-mode` to tmux config, run rmpc from shell.

### What terminal emulator are you running rmpc in?

Tmux within Alacritty

### rmpc debuginfo

<details>
  <summary>rmpc debuginfo</summary>

  ```sh
rmpc 0.9.0 git Arch Linux

Config path          ~/.config/rmpc/config.ron
Theme path           None

MPD:
Address              "127.0.0.1:6600"
Resolved Address     IpAndPort("127.0.0.1:6600")
MPD_HOST             unset
MPD_PORT             unset

Youtube playback:
Cache dir            None
ffmpeg               installed       ffmpeg version n8.0 Copyright (c) 2000-2025 the FFmpeg developers
ffprobe              installed       ffprobe version n8.0 Copyright (c) 2007-2025 the FFmpeg developers
yt-dlp               installed       2025.10.22
python3              installed       Python 3.13.7
python-mutagen       not installed   NOT PRESENT

Image protocol:
Requested            Auto
Resolved             Block
TMUX                 true
ueberzugpp           not installed   Version not available

Visualizer:
cava                 not installed   Version not available
  ```
</details>

### Config file

<details>
  <summary>rmpc config</summary>

  ```ron
Paste the output here
  ```
</details>

### Relevant log output

<details>
  <summary>rmpc log</summary>

  ```
Paste the contents here
  ```
</details>

**Comment by mierak** [comment]
Please try [building from source](https://rmpc.mierak.dev/development/#dev-setup-and-running-rmpc-from-the-source-code). I think this should have been fixed in https://github.com/mierak/rmpc/pull/726.

**Comment by aris-mav** [comment]
Just tried that, unfortunately it does not fix the issue.
For reference: 

<img width="1132" height="1438" alt="Image" src="https://github.com/user-attachments/assets/508bc02a-558a-4e78-a693-93785e888743" />

**Comment by mierak** [comment]
Alright, well good news is, I can reproduce this. ~~But only in alacritty and foot, neither of ghostty/kitty/wezterm seem to have this issue.~~ Bad news is, I have no idea what is causing it at this point, anyway I will look into it a bit more.

**Comment by aris-mav** [comment]
Probably some escape sequence problem; `alt-[` seems somewhat equivalent to `^[[` and that might cause the issue?

**Comment by mierak** [comment]
Yeah, its most likely some sequence rmpc sends to the terminal at startup to determine support for image protocol/kitty keyboard protocol etc. But what exactly is causing that will need a closer look.

**Comment by mierak** [comment]
Can you try forcing rmpc(on latest master) to use a [specific image method](https://rmpc.mierak.dev/release-0-10-0/configuration/album-art/#method) instead of an auto detection? I believe it should not hit the path which makes this behavior appear. For alacritty that would be either ueberzugpp or block.

The issue is caused by rmpc querying the terminal for support of various protocol and having to use tmux passthrough sequences which results in tmux falsely interpreting them as keyboard input. The passthrough has to be used, otherwise rmpc cannot reliably check for support of sixel, kitty graphics protocol etc. Even other programs like yazi encounter this issue. I will look into this a little bit more if I can hack my way around it, but it is very likely that this collision of inputs cannot really be resolved easily or at all on rmpc's end.

**Comment by aris-mav** [comment]
I can confirm `Auto` is what is causing the issue, thank you for looking into it!

**Comment by mierak** [comment]
Yeah, I dont think there is much I can do to work around this, I looked around if there are any options like disabling the keybinds in tmux temporarily on startup etc but found no satisfactory option.

I will have to suggest either changing the hotkey or not using the auto detection, sorry :(

**Comment by aris-mav** [comment]
Thanks, it's not a big issue anyway, I just changed my keymap just in case it would interfere with any other programs. 
Just thought it might be good to report anyway, in case others encounter the same.
Could perhaps mention this behaviour as a disclaimer somewhere in the docs?
I know it's quite a unique edge-case, but you never know.

**Comment by davidsierradz** [comment]
Sorry to bump this issue, I'm seeing something similar with tmux 3.6a but with the following binding: `bind-key -T root M-P previous-window`, I disabled album_art with method None

[tmux-out-1359988.log](https://github.com/user-attachments/files/25850454/tmux-out-1359988.log)

```
rmpc 0.11.0 git 0.11.0

Image protocol:
Requested            None
Resolved             None
ueberzugpp           not installed   Version not available

System:
TMUX                 true            Some("3.6a")
TMUX passthrough     true
$TERM                tmux-256color
$TERM_PROGRAM        unset
Emulator             Unknown
Kitty Keyboard       false
ZELLIJ               false
```

Thanks

**Comment by mierak** [comment]
Hi, unless I am missing something extremely obvious there is simply nothing I can do. Rmpc sends ESC + P as a part of [tmux passthrough sequence](https://github.com/tmux/tmux/wiki/FAQ#what-is-the-passthrough-escape-sequence-and-how-do-i-use-it) (note the ESC + P + tmux at the start of the sequence). Your M+P keybind then wrongly interprets this as a keypress and triggers. I can only suggest the same thing as I did before, sorry.

**Comment by davidsierradz** [comment]
Thanks, I was hoping that disabling some feature would prevent the querying. I could live with moving the binding.
